[build-system]
requires=["setuptools"]
build-backend = "setuptools

[project]
name="pytoxtest"
version ="0.0.0"
dependencies= [
    "mypy", "pytest", "tox", "black", "flake8" 
]
descriptions = "Just to test out github actions workflow with python tox"
