# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix: 
        python: ["3.9", "3.10" , "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{matrix.python}}
    - name: Install tox and deps
      run: |
        pip install tox
        pip install flake8 pytest black mypy
    - name: Run tox
      run: 
        tox -e test
    - name: Run formatting
      run: 
        tox -e format
    - name: Run lint 
      run: 
        tox -e lint 
    
